from flask import Flask, render_template, request, send_file
import os
import pdfplumber
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

app = Flask(__name__)

UPLOAD_FOLDER = "uploads"
app.config["UPLOAD_FOLDER"] = UPLOAD_FOLDER

skills = [
    "Python",
    "C",
    "C++",
    "Java",
    "SQL",
    "HTML",
    "CSS",
    "JavaScript",
    "Flask",
    "Git",
    "AWS",
    "Machine Learning",
    "OOP",
    "Data Structures",
    "Linux",
    "Embedded Systems",
    "Arduino"
]

role_skills = {
    "Python Developer": [
        "Python", "Flask", "SQL", "Git", "OOP"
    ],

    "Java Developer": [
        "Java", "SQL", "Git", "OOP"
    ],

    "Data Analyst": [
        "Python", "SQL", "Machine Learning"
    ],

    "AI/ML Engineer": [
        "Python", "Machine Learning", "SQL", "Git"
    ],

    "Frontend Developer": [
        "HTML", "CSS", "JavaScript", "Git"
    ],

    "Cloud Engineer": [
        "AWS", "Linux", "Python", "Git"
    ]
}

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from reportlab.lib import colors
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet


def generate_pdf(data):
    filepath = os.path.join("uploads", "report.pdf")

    doc = SimpleDocTemplate(filepath)
    styles = getSampleStyleSheet()

    elements = []

    # Title
    title = Paragraph(
        "AI RESUME ANALYSIS REPORT",
        styles['Title']
    )

    elements.append(title)
    elements.append(Spacer(1, 15))

    # Candidate Information Table
    info_data = [
        ["Role Applied", data["role"]],
        ["Target Company", data["company"]],
        ["ATS Score", f"{data['ats_score']}%"],
        ["Performance Level", data["level"]]
    ]

    info_table = Table(info_data, colWidths=[150, 300])

    info_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE')
    ]))

    elements.append(info_table)
    elements.append(Spacer(1, 20))

    # Matched Skills Table
    elements.append(
        Paragraph("MATCHED SKILLS", styles['Heading2'])
    )

    matched_rows = [["Skill"]]

    for skill in data["matched_skills"]:
        matched_rows.append([skill])

    matched_table = Table(matched_rows, colWidths=[450])

    matched_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.lightgreen),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))

    elements.append(matched_table)
    elements.append(Spacer(1, 20))

    # Missing Skills Table
    elements.append(
        Paragraph("MISSING SKILLS", styles['Heading2'])
    )

    missing_rows = [["Skill"]]

    for skill in data["missing_skills"]:
        missing_rows.append([skill])

    missing_table = Table(missing_rows, colWidths=[450])

    missing_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.pink),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))

    elements.append(missing_table)
    elements.append(Spacer(1, 20))

    # Suggestions Table
    elements.append(
        Paragraph("RECOMMENDATIONS", styles['Heading2'])
    )

    suggestion_rows = [["Recommendation"]]

    for item in data["suggestions"]:
        suggestion_rows.append([item])

    suggestion_table = Table(
        suggestion_rows,
        colWidths=[450]
    )

    suggestion_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.lightblue),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))

    elements.append(suggestion_table)
    elements.append(Spacer(1, 20))

    footer = Paragraph(
        "Generated by AI Resume Analyzer",
        styles['Italic']
    )

    elements.append(footer)

    doc.build(elements)

@app.route('/')
def home():
    return render_template('index.html')


@app.route('/upload', methods=['POST'])
def upload():

    file = request.files['resume']

    role = request.form['role']
    company = request.form['company']

    if file:

        filepath = os.path.join(
            app.config['UPLOAD_FOLDER'],
            file.filename
        )

        file.save(filepath)

        import pdfplumber

        text = ""

        with pdfplumber.open(filepath) as pdf:

            for page in pdf.pages:

                extracted = page.extract_text()

                if extracted:
                    text += extracted

        found_skills = []

        for skill in skills:

            if skill.lower() in text.lower():

                found_skills.append(skill)
                
        required_skills = role_skills.get(role,[])

        matched = len(set(found_skills) & set(required_skills))

        if len(required_skills) > 0:
          score = (matched / len(required_skills)) * 100
        else:
          score = 0

        ats_score = round(score)
 
        matched_skills = []

        for skill in required_skills:
            if skill in found_skills:
               matched_skills.append(skill)

        missing_skills = []

        for skill in required_skills:
            if skill not in found_skills:
               missing_skills.append(skill)

        suggestions = []

        for skill in missing_skills:
           suggestions.append(f"Learn {skill}")

        if ats_score >= 85:
             level = "Excellent"
        elif ats_score >= 70:
             level = "Good"
        elif ats_score >= 50:
             level = "Average"
        else:
             level = "Needs Improvement"


        result_data = {
            "role": role,
            "company": company,
            "ats_score": ats_score,
            "level": level,
            "matched_skills": matched_skills,
            "missing_skills": missing_skills,
            "suggestions": suggestions
        }

        generate_pdf(result_data)

        return render_template(
   "result.html",
    found_skills=found_skills,
    required_skills=required_skills,
    matched_skills=matched_skills,
    missing_skills=missing_skills,
    score=round(score),
    ats_score=ats_score,
    suggestions=suggestions,
    role=role,
    company=company,
    level=level
)
        
        
    return "No file selected"


from flask import send_file

@app.route('/download')
def download():
    return send_file("uploads/report.pdf", as_attachment=True)

if __name__ == "__main__":
    app.run(debug=True)